image: ubuntu1804
install:
- sudo apt update && sudo apt install -y build-essential curl cmake libboost-all-dev libssl-dev libsodium-dev python-pip python-dev
build_script:
- mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_GCOV=1 && make
test_script:
- env CTEST_OUTPUT_ON_FAILURE=1 make test