sudo: false
language: cpp
compiler:
  - gcc
  # - clang
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5.0
    - g++-5.0
    - libboost-all-dev

before_install:
  - pip install --user cpp-coveralls
script:
  - mkdir build && cd build && cmake .. && make && make check
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
