version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: Get building tools
          command: apt update && apt install -y build-essential curl cmake libboost-all-dev libssl-dev libsodium-dev python-pip python-dev lcov
      - run:
          name: Prepare conan
          command: python -m pip install --upgrade pip
      - run:
          name: Building project
          command: mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_GCOV=1 && make
      - run:
          name: Testing project
          command: cd build && env CTEST_OUTPUT_ON_FAILURE=1 make test
      - run:
          name: Generating Coverage info
          command: cd build && lcov --capture --directory src --output-file temp.info && lcov --remove temp.info "/usr/include/*" "*/google/*" "*/include/*" "*/tests/*" > coverage.info && lcov --list coverage.info
    #   - run:
    #       name: Uploading Coverage info
    #       command: cd build && bash <(curl -s https://codecov.io/bash) -t 2a2cf36f-81d6-43b9-abba-d5955cb0cafe        
      - run:
          name: Sending coverall info
          command: pip install codecov && cd build && codecov --token 2a2cf36f-81d6-43b9-abba-d5955cb0cafe --root src