version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: Get building tools
          command: apt update && apt install -y build-essential cmake libboost-all-dev libssl-dev python-pip python-dev
      - run:
          name: Enabling coverage
          command: pip install --user cpp-coveralls
      - run:
          name: Building project
          command: mkdir -p build && cd build && cmake .. && make
      - run:
          name: Testing project
          command: cd build && env CTEST_OUTPUT_ON_FAILURE=1 make test
    #   - run:
    #       name: Sending coverall info
    #       command: coveralls --exclude lib --exclude tests --gcov-options '\-lp'